### PR TITLE
Add check to prevent key errors for lacking metadata in neon_soil_example

### LINKED ISSUE #28: Defensive programming/decrease assumptions: Try/catch for `KeyError: 'geo_loc_name'`
in `NEON_soil_metadata/python/neon_soil_metadata_visual_exploration.ipynb`

```python
coordinates = set()
geo_locs = set()
dates = set()
for samp in all_results:
    lat_lon = f"{samp['lat_lon']['latitude']},{samp['lat_lon']['longitude']}"
    coordinates.add(lat_lon)
    geo_locs.add(samp["geo_loc_name"]["has_raw_value"])
    dates.add(samp["collection_date"]["has_raw_value"])
```

> ```
> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> Cell In[4], line 10
>       8     lat_lon = f"{samp['lat_lon']['latitude']},{samp['lat_lon']['longitude']}"
>       9     coordinates.add(lat_lon)
> ---> 10     geo_locs.add(samp["geo_loc_name"]["has_raw_value"])
>      11     dates.add(samp["collection_date"]["has_raw_value"])
>      12 print(f"Number of NEON coordinates: {len(coordinates)}")
> 
> KeyError: 'geo_loc_name'
> ```

### PR DESCRIPTION
**Pull request by kheal**
Closes #28.

Issue arose from bio samples that must have been ingested after our initial creation of the notebooks.  Some of the new bio samples do not have slots for `geo_loc_name` and are throwing a key error. I've added a check that subsets samples only for those with a `collection_date`, `geo_loc_name` and `lat_lon` before adding those data to downstream analyses.

### CODE REVIEW

**Comment by kheal** [comment]
Just as a reminder, I find it easiest to review by looking at the rendered notebook in the branch (https://nbviewer.org/github/microbiomedata/notebook_hackathons/blob/neon_metadata_keyerror/NEON_soil_metadata/python/neon_soil_metadata_visual_exploration.ipynb) and its associated google colab (https://colab.research.google.com/github/microbiomedata/notebook_hackathons/blob/neon_metadata_keyerror/NEON_soil_metadata/python/neon_soil_metadata_visual_exploration.ipynb).  

Once the PR is merged into main, the notebooks will be accessible via the links in this readme: https://github.com/microbiomedata/nmdc_notebooks/tree/main/NEON_soil_metadata#readme.

**Comment by brynnz22** [comment]
@kheal  are the changes in cell 4?:

```
# Check if samp has keys that correspond to primary metadata
    if set(['lat_lon', 'geo_loc_name', 'collection_date']).issubset(samp):
```

**Comment by kheal** [comment]
Yep!  And then a few spots down below that used to reference `all_results ` now reference `all_full_results`.

**Review by brynnz22 — APPROVED** [review]
Thanks for diff link!

**Comment by kheal** [comment]
To review: https://app.reviewnb.com/microbiomedata/nmdc_notebooks/pull/35/

**Pull request merged**
